-- Creación de la tabla para guardar las actas en formato HTML
create table if not exists actas_documentos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  id_logia int not null,
  titulo text,
  contenido_html text,
  fecha_creacion timestamp with time zone default timezone('utc'::text, now())
);

-- Habilitar RLS (Row Level Security)
alter table actas_documentos enable row level security;

-- Política de lectura: Todos los autenticados pueden ver (ajustar según necesidad)
create policy "Ver todas las actas"
on actas_documentos for select
to authenticated
using (true); -- O filtrar por id_logia si aplica

-- Política de inserción: Todos los autenticados pueden insertar
create policy "Insertar actas"
on actas_documentos for insert
to authenticated
with check (true);

-- Política de edición: Solo el creador o rol específico (aquí abierto para ejemplo)
create policy "Editar actas"
on actas_documentos for update
to authenticated
using (true);

-- Crear el bucket 'firmas' si no existe (aunque ya se intentó en otro script)
insert into storage.buckets (id, name, public)
values ('firmas', 'firmas', true)
on conflict (id) do nothing;

-- Política para el bucket 'firmas'
create policy "Subir firmas"
on storage.objects for insert
to authenticated
with check (bucket_id = 'firmas');

create policy "Ver firmas"
on storage.objects for select
to public
using (bucket_id = 'firmas');
