// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlLK_p5HkQe0vdL9EcVtPwrBM6Jh-elEI',
    appId: '1:889586843338:web:a2191c925fbacffba6fe33',
    messagingSenderId: '889586843338',
    projectId: 'milogianotifications',
    authDomain: 'milogianotifications.firebaseapp.com',
    storageBucket: 'milogianotifications.firebasestorage.app',
    measurementId: 'G-4NKJ3KD59Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHPnZ_k5NpPPN4Wn4gO5gBziIsx9RF08g',
    appId: '1:889586843338:android:4dafaed19cb0beb6a6fe33',
    messagingSenderId: '889586843338',
    projectId: 'milogianotifications',
    storageBucket: 'milogianotifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVE7h_dzy7s7DwQ7EYD4N8nPD1cNIwDy4',
    appId: '1:889586843338:ios:e302f97475612093a6fe33',
    messagingSenderId: '889586843338',
    projectId: 'milogianotifications',
    storageBucket: 'milogianotifications.firebasestorage.app',
    iosBundleId: 'com.example.milogia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVE7h_dzy7s7DwQ7EYD4N8nPD1cNIwDy4',
    appId: '1:889586843338:ios:e302f97475612093a6fe33',
    messagingSenderId: '889586843338',
    projectId: 'milogianotifications',
    storageBucket: 'milogianotifications.firebasestorage.app',
    iosBundleId: 'com.example.milogia',
  );

}